"""Add Day 3 models and fields

Revision ID: 4c90075ce1da
Revises: 649501766130
Create Date: 2026-08-20 20:40:54.134038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c90075ce1da'
down_revision: Union[str, None] = '649501766130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE worksessionstatusenum ADD VALUE 'failed'")
    op.execute("ALTER TYPE worksessionstatusenum ADD VALUE 'rescheduled'")
    
    op.create_table('daily_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('estimation_accuracy', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reviews_date'), 'daily_reviews', ['date'], unique=True)
    op.create_index(op.f('ix_daily_reviews_id'), 'daily_reviews', ['id'], unique=False)
    op.create_table('weekly_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('estimation_accuracy', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_reviews_id'), 'weekly_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_reviews_week_start_date'), 'weekly_reviews', ['week_start_date'], unique=True)
    failure_category_enum = sa.Enum('distraction', 'underestimated', 'blocked', 'fatigue', 'priority_shift', 'other', name='failurecategoryenum')
    failure_category_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('work_sessions', sa.Column('failure_category', failure_category_enum, nullable=True))
    op.add_column('work_sessions', sa.Column('failure_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_sessions', 'failure_reason')
    op.drop_column('work_sessions', 'failure_category')
    op.execute("DROP TYPE failurecategoryenum")
    op.drop_index(op.f('ix_weekly_reviews_week_start_date'), table_name='weekly_reviews')
    op.drop_index(op.f('ix_weekly_reviews_id'), table_name='weekly_reviews')
    op.drop_table('weekly_reviews')
    op.drop_index(op.f('ix_daily_reviews_id'), table_name='daily_reviews')
    op.drop_index(op.f('ix_daily_reviews_date'), table_name='daily_reviews')
    op.drop_table('daily_reviews')
    # ### end Alembic commands ###
