"""Day 3 revised models

Revision ID: 4f1a09eb8657
Revises: 4c90075ce1da
Create Date: 2026-08-20 20:56:39.019786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f1a09eb8657'
down_revision: Union[str, None] = '4c90075ce1da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE taskstatusenum ADD VALUE IF NOT EXISTS 'rescheduled'")
    
    op.create_table('failures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('failure_type', sa.Enum('poor_estimation', 'lack_of_knowledge', 'task_too_difficult', 'task_unclear', 'distraction', 'fatigue', 'unexpected_responsibility', 'procrastination', 'technical_problem', 'emotional_resistance', 'scheduling_problem', 'missing_dependency', 'other', name='failuretypeenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('impact', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['work_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failures_id'), 'failures', ['id'], unique=False)
    op.create_table('corrective_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('failure_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('new_plan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['failure_id'], ['failures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrective_actions_id'), 'corrective_actions', ['id'], unique=False)
    op.add_column('daily_reviews', sa.Column('review_date', sa.Date(), nullable=False))
    op.add_column('daily_reviews', sa.Column('summary', sa.String(), nullable=False))
    op.drop_index('ix_daily_reviews_date', table_name='daily_reviews')
    op.create_index(op.f('ix_daily_reviews_review_date'), 'daily_reviews', ['review_date'], unique=True)
    op.drop_column('daily_reviews', 'date')
    op.drop_column('daily_reviews', 'reliability_score')
    op.drop_column('daily_reviews', 'notes')
    op.drop_column('daily_reviews', 'estimation_accuracy')
    op.add_column('weekly_reviews', sa.Column('weekly_plan_id', sa.UUID(), nullable=False))
    op.add_column('weekly_reviews', sa.Column('summary', sa.String(), nullable=False))
    op.drop_index('ix_weekly_reviews_week_start_date', table_name='weekly_reviews')
    op.create_unique_constraint(None, 'weekly_reviews', ['weekly_plan_id'])
    op.create_foreign_key(None, 'weekly_reviews', 'weekly_plans', ['weekly_plan_id'], ['id'], ondelete='CASCADE')
    op.drop_column('weekly_reviews', 'estimation_accuracy')
    op.drop_column('weekly_reviews', 'reliability_score')
    op.drop_column('weekly_reviews', 'notes')
    op.drop_column('weekly_reviews', 'week_start_date')
    op.drop_column('work_sessions', 'failure_reason')
    op.drop_column('work_sessions', 'failure_category')
    op.execute("DROP TYPE failurecategoryenum")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE failurecategoryenum AS ENUM ('distraction', 'underestimated', 'blocked', 'fatigue', 'priority_shift', 'other')")
    op.add_column('work_sessions', sa.Column('failure_category', postgresql.ENUM('distraction', 'underestimated', 'blocked', 'fatigue', 'priority_shift', 'other', name='failurecategoryenum'), autoincrement=False, nullable=True))
    op.add_column('work_sessions', sa.Column('failure_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('weekly_reviews', sa.Column('week_start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('weekly_reviews', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('weekly_reviews', sa.Column('reliability_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('weekly_reviews', sa.Column('estimation_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'weekly_reviews', type_='foreignkey')
    op.drop_constraint(None, 'weekly_reviews', type_='unique')
    op.create_index('ix_weekly_reviews_week_start_date', 'weekly_reviews', ['week_start_date'], unique=False)
    op.drop_column('weekly_reviews', 'summary')
    op.drop_column('weekly_reviews', 'weekly_plan_id')
    op.add_column('daily_reviews', sa.Column('estimation_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('daily_reviews', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('daily_reviews', sa.Column('reliability_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('daily_reviews', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_daily_reviews_review_date'), table_name='daily_reviews')
    op.create_index('ix_daily_reviews_date', 'daily_reviews', ['date'], unique=False)
    op.drop_column('daily_reviews', 'summary')
    op.drop_column('daily_reviews', 'review_date')
    op.drop_index(op.f('ix_corrective_actions_id'), table_name='corrective_actions')
    op.drop_table('corrective_actions')
    op.drop_index(op.f('ix_failures_id'), table_name='failures')
    op.drop_table('failures')
    # ### end Alembic commands ###
